// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9VkMKq3rdG4TKIihKL0sQXI8OFFoUd0',
    appId: '1:16783753691:web:c5bf067d6841472052a7fe',
    messagingSenderId: '16783753691',
    projectId: 'todo-9e026',
    authDomain: 'todo-9e026.firebaseapp.com',
    storageBucket: 'todo-9e026.firebasestorage.app',
    measurementId: 'G-SX5P4QLN79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfRW1x_qQBYmutoxZb99_FEyHF34Zc-8M',
    appId: '1:16783753691:android:588783950835c59152a7fe',
    messagingSenderId: '16783753691',
    projectId: 'todo-9e026',
    storageBucket: 'todo-9e026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkwklCR_cE6Lq1-tChEI8xp6I_tqccQYo',
    appId: '1:16783753691:ios:fe9e27598918db4652a7fe',
    messagingSenderId: '16783753691',
    projectId: 'todo-9e026',
    storageBucket: 'todo-9e026.firebasestorage.app',
    iosBundleId: 'com.kalkidan.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkwklCR_cE6Lq1-tChEI8xp6I_tqccQYo',
    appId: '1:16783753691:ios:779d2f7e11d80b7e52a7fe',
    messagingSenderId: '16783753691',
    projectId: 'todo-9e026',
    storageBucket: 'todo-9e026.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR9VkMKq3rdG4TKIihKL0sQXI8OFFoUd0',
    appId: '1:16783753691:web:26589011c743f74e52a7fe',
    messagingSenderId: '16783753691',
    projectId: 'todo-9e026',
    authDomain: 'todo-9e026.firebaseapp.com',
    storageBucket: 'todo-9e026.firebasestorage.app',
    measurementId: 'G-NYT9P0Q73B',
  );
}
